/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeAlumno;
import org.emersonhernandez.modelo.Alumno;

/**
 *
 * @author Emerson
 */
public class ActulizarAlumnos extends javax.swing.JInternalFrame {
public static ControlDeAlumno controladorActualizar = ControlDeAlumno.getInstancia();

    /**
     * Creates new form VistaActualizarAlumno
     */
    public ActulizarAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarAlumno = new javax.swing.JPanel();
        lblAntiguoIdActualizarAlumno = new javax.swing.JLabel();
        txtAntiguoIdActualizarAlumno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNuevoIdActualizarAlumno = new javax.swing.JLabel();
        txtNuevoIdActualizarAlumno = new javax.swing.JTextField();
        lblNuevoNombreActualizarAlumno = new javax.swing.JLabel();
        txtNuevoNombreActualizarAlumno = new javax.swing.JTextField();
        lblNuevaCarreraActualizarAlumno = new javax.swing.JLabel();
        txtNuevaCarreraActualizarAlumno = new javax.swing.JTextField();
        lblNuevoTelefonoActualizarAlumno = new javax.swing.JLabel();
        txtNuevoTelefonoActualizarAlumno = new javax.swing.JTextField();
        botonActualizarAlumno = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblAntiguoIdActualizarAlumno.setText("Ingrese Antiguo ID:");

        lblNuevoIdActualizarAlumno.setText("Ingrese Nuevo ID:");

        lblNuevoNombreActualizarAlumno.setText("Ingrese Nuevo Nombre:");

        lblNuevaCarreraActualizarAlumno.setText("Ingrese Nueva Carrera:");

        lblNuevoTelefonoActualizarAlumno.setText("Ingrese Nuevo Telefono: ");

        botonActualizarAlumno.setText("Actualizar");
        botonActualizarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarAlumnoLayout = new javax.swing.GroupLayout(panelActualizarAlumno);
        panelActualizarAlumno.setLayout(panelActualizarAlumnoLayout);
        panelActualizarAlumnoLayout.setHorizontalGroup(
            panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                                .addComponent(lblNuevoNombreActualizarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNuevoNombreActualizarAlumno))
                            .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                                        .addComponent(lblAntiguoIdActualizarAlumno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAntiguoIdActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                                        .addComponent(lblNuevoIdActualizarAlumno)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNuevoIdActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNuevaCarreraActualizarAlumno)
                                    .addComponent(lblNuevoTelefonoActualizarAlumno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNuevaCarreraActualizarAlumno)
                                    .addComponent(txtNuevoTelefonoActualizarAlumno))))))
                .addContainerGap())
            .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(botonActualizarAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelActualizarAlumnoLayout.setVerticalGroup(
            panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntiguoIdActualizarAlumno)
                    .addComponent(txtAntiguoIdActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoIdActualizarAlumno)
                    .addComponent(txtNuevoIdActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoNombreActualizarAlumno)
                    .addComponent(txtNuevoNombreActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevaCarreraActualizarAlumno)
                    .addComponent(txtNuevaCarreraActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoTelefonoActualizarAlumno)
                    .addComponent(txtNuevoTelefonoActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonActualizarAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarAlumnoActionPerformed
    Alumno nuevoAlumno = new Alumno();
        int id = Integer.parseInt(txtAntiguoIdActualizarAlumno.getText());

        for(Alumno alumnoAntiguo: controladorActualizar.getListaDeAlumnos()){
            if(alumnoAntiguo.getCarnet()== id){
                nuevoAlumno.setCarnet(Integer.parseInt(txtNuevoIdActualizarAlumno.getText()));
                nuevoAlumno.setNombre(txtNuevoNombreActualizarAlumno.getText());
                nuevoAlumno.setCarrera(txtNuevaCarreraActualizarAlumno.getText());
                nuevoAlumno.setTelefono(txtNuevoTelefonoActualizarAlumno.getText());

                controladorActualizar.actualizarAlumno(alumnoAntiguo, nuevoAlumno);
            }
        }
        this.setVisible(false);
        txtAntiguoIdActualizarAlumno.setText("");
        txtNuevoIdActualizarAlumno.setText("");
        txtNuevoNombreActualizarAlumno.setText("");
        txtNuevaCarreraActualizarAlumno.setText("");
        txtNuevoTelefonoActualizarAlumno.setText("");  
            // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarAlumno;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAntiguoIdActualizarAlumno;
    private javax.swing.JLabel lblNuevaCarreraActualizarAlumno;
    private javax.swing.JLabel lblNuevoIdActualizarAlumno;
    private javax.swing.JLabel lblNuevoNombreActualizarAlumno;
    private javax.swing.JLabel lblNuevoTelefonoActualizarAlumno;
    private javax.swing.JPanel panelActualizarAlumno;
    private javax.swing.JTextField txtAntiguoIdActualizarAlumno;
    private javax.swing.JTextField txtNuevaCarreraActualizarAlumno;
    private javax.swing.JTextField txtNuevoIdActualizarAlumno;
    private javax.swing.JTextField txtNuevoNombreActualizarAlumno;
    private javax.swing.JTextField txtNuevoTelefonoActualizarAlumno;
    // End of variables declaration//GEN-END:variables
}
