/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeAlumno;

/**
 *
 * @author Emerson
 */
public class BorrarAlumno extends javax.swing.JInternalFrame {
public static ControlDeAlumno controlEliminar = ControlDeAlumno.getInstancia();

    /**
     * Creates new form BorrarAlumno
     */
    public BorrarAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorrarAlumno = new javax.swing.JPanel();
        lblBorrarAlumno = new javax.swing.JLabel();
        txtBorrarAlumno = new javax.swing.JTextField();
        botonEliminarAlumno = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblBorrarAlumno.setText("Carnet:");

        botonEliminarAlumno.setText("Borrar");
        botonEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorrarAlumnoLayout = new javax.swing.GroupLayout(panelBorrarAlumno);
        panelBorrarAlumno.setLayout(panelBorrarAlumnoLayout);
        panelBorrarAlumnoLayout.setHorizontalGroup(
            panelBorrarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorrarAlumnoLayout.createSequentialGroup()
                .addGroup(panelBorrarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorrarAlumnoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelBorrarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorrarAlumnoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBorrarAlumno)))
                    .addGroup(panelBorrarAlumnoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(botonEliminarAlumno)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelBorrarAlumnoLayout.setVerticalGroup(
            panelBorrarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorrarAlumnoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblBorrarAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEliminarAlumno)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorrarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorrarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAlumnoActionPerformed
        controlEliminar.eliminarAlumno(Integer.parseInt(txtBorrarAlumno.getText()));    
        this.setVisible(false);  
        txtBorrarAlumno.setText("");          // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarAlumno;
    private javax.swing.JLabel lblBorrarAlumno;
    private javax.swing.JPanel panelBorrarAlumno;
    private javax.swing.JTextField txtBorrarAlumno;
    // End of variables declaration//GEN-END:variables
}
