/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.modelo.Profesor;
import org.emersonhernandez.controlador.ControlDeProfesor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author emerh
 */
public class VerProfesor extends javax.swing.JInternalFrame {
public static ControlDeProfesor control= ControlDeProfesor.getInstancia();
    /**
     * Creates new form VerProfesor
     */
    public VerProfesor() {
        initComponents();
    }
    public void mostrarDatos(){
        
         String [] encabezados = {"ID","Nombre","Telefono","Carrera"};
       int cantidadDeElementos = control.cantidadDeProfesores();

       DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
       tablaProfesores.setModel(cabeceraDeTabla);
       TableModel listaDeDatos = tablaProfesores.getModel();

       for(int i=0; i<cantidadDeElementos; i++){
       Profesor alumno = control.getListaDeProfesores().get(i);
       listaDeDatos.setValueAt(alumno.getCarnet(), i, 0);
       listaDeDatos.setValueAt(alumno.getNombre(), i, 1);
       listaDeDatos.setValueAt(alumno.getTelefono(), i, 2);
       listaDeDatos.setValueAt(alumno.getCarrera(), i, 3);


       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProfesores = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Carnet", "Nombre", "Materia", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tablaProfesores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProfesores;
    // End of variables declaration//GEN-END:variables
}
