/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.modelo.Cursos;
import org.emersonhernandez.controlador.ControlDeCursos;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author emerh
 */
public class VistaVerCursos extends javax.swing.JInternalFrame {
public static ControlDeCursos controlCurso = ControlDeCursos.getInstancia();
    /**
     * Creates new form VistaVerCursos
     */
    public VistaVerCursos() {
        initComponents();
    }
    
    public void verCursos(){
       String [] encabezados = {"ID","Nombre","Profesor","Carrera"};
       int cantidadDeElementos = controlCurso.cantidadDeCursos();

       DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
       TablaVerCursos.setModel(cabeceraDeTabla);
       TableModel listaDeDatos = TablaVerCursos.getModel();

       for(int i=0; i<cantidadDeElementos; i++){
       Cursos cursos = controlCurso.getListaDeCursos().get(i);
       listaDeDatos.setValueAt(cursos.getId(), i, 0);
       listaDeDatos.setValueAt(cursos.getNombre(), i, 1);
       listaDeDatos.setValueAt(cursos.getProfesor(), i, 2);
       listaDeDatos.setValueAt(cursos.getCarrera(), i, 3);


       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTablaCursos = new javax.swing.JScrollPane();
        TablaVerCursos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        TablaVerCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Curso", "Nombre Curso", "Profesor Curso", "Carrera Curso"
            }
        ));
        scrollTablaCursos.setViewportView(TablaVerCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTablaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollTablaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVerCursos;
    private javax.swing.JScrollPane scrollTablaCursos;
    // End of variables declaration//GEN-END:variables
}
