/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeCarrera;
import org.emersonhernandez.modelo.Carrera;

/**
 *
 * @author emerh
 */
public class VistaActualizarCarrera extends javax.swing.JInternalFrame {
public static ControlDeCarrera myCarrera = ControlDeCarrera.getInstancia();
    /**
     * Creates new form VistaActualizarCarrera
     */
    public VistaActualizarCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAntiguoIdActualizarCarrera = new javax.swing.JLabel();
        txtAntiguoIdActualizarCarrera = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNuevoIdActualizarCarrera = new javax.swing.JLabel();
        txtNuevoIdActualizarCarrera = new javax.swing.JTextField();
        lblNuevoNombreActualizarCarrera = new javax.swing.JLabel();
        txtNuevoNombreActualizarCarrera = new javax.swing.JTextField();
        lblNuevaSeccionActualizarCarrera = new javax.swing.JLabel();
        txtNuevaSeccionActualizarCarrera = new javax.swing.JTextField();
        botonActualizarCarrera = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblAntiguoIdActualizarCarrera.setText("ID Antiguo");

        lblNuevoIdActualizarCarrera.setText("Nuevo ID");

        lblNuevoNombreActualizarCarrera.setText("Nuevo Nombre");

        lblNuevaSeccionActualizarCarrera.setText("Nueva Seccion");

        botonActualizarCarrera.setText("Actualizar");
        botonActualizarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAntiguoIdActualizarCarrera)
                        .addGap(72, 72, 72)
                        .addComponent(txtAntiguoIdActualizarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNuevoIdActualizarCarrera)
                            .addComponent(lblNuevoNombreActualizarCarrera)
                            .addComponent(lblNuevaSeccionActualizarCarrera))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonActualizarCarrera)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNuevoIdActualizarCarrera)
                                .addComponent(txtNuevoNombreActualizarCarrera)
                                .addComponent(txtNuevaSeccionActualizarCarrera)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAntiguoIdActualizarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAntiguoIdActualizarCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoIdActualizarCarrera)
                    .addComponent(txtNuevoIdActualizarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoNombreActualizarCarrera)
                    .addComponent(txtNuevoNombreActualizarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevaSeccionActualizarCarrera)
                    .addComponent(txtNuevaSeccionActualizarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonActualizarCarrera)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarCarreraActionPerformed
        // TODO add your handling code here:
        Carrera newCarrera = new Carrera();
        int id = Integer.parseInt(txtAntiguoIdActualizarCarrera.getText());

        for(Carrera alumnoAntiguo: myCarrera.getListaDeCarreras()){
            if(alumnoAntiguo.getId()== id){
                newCarrera.setCarnet(Integer.parseInt(txtNuevoIdActualizarCarrera.getText()));
                newCarrera.setNombre(txtNuevoNombreActualizarCarrera.getText());
                newCarrera.setSeccion(txtNuevaSeccionActualizarCarrera.getText());
                

                myCarrera.actualizarCarrera(alumnoAntiguo, newCarrera);
            }
        }
        this.setVisible(false);
        txtAntiguoIdActualizarCarrera.setText("");
        txtNuevoIdActualizarCarrera.setText("");
        txtNuevoNombreActualizarCarrera.setText("");
        txtNuevaSeccionActualizarCarrera.setText("");
       
    }//GEN-LAST:event_botonActualizarCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCarrera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAntiguoIdActualizarCarrera;
    private javax.swing.JLabel lblNuevaSeccionActualizarCarrera;
    private javax.swing.JLabel lblNuevoIdActualizarCarrera;
    private javax.swing.JLabel lblNuevoNombreActualizarCarrera;
    private javax.swing.JTextField txtAntiguoIdActualizarCarrera;
    private javax.swing.JTextField txtNuevaSeccionActualizarCarrera;
    private javax.swing.JTextField txtNuevoIdActualizarCarrera;
    private javax.swing.JTextField txtNuevoNombreActualizarCarrera;
    // End of variables declaration//GEN-END:variables
}
