/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.modelo.Alumno;
import org.emersonhernandez.controlador.ControlDeAlumno;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Emerson
 */
public class VistaVerAlumno extends javax.swing.JInternalFrame {
public static ControlDeAlumno controlAlumno = ControlDeAlumno.getInstancia();

    /**
     * Creates new form VistaVerAlumno
     */
    public VistaVerAlumno() {
        initComponents();
    }
    public void verDatos(){
       String [] encabezados = {"Carnet","Nombre","Telefono","Carrera"};
       int cantidadDeElementos = controlAlumno.cantidadDeElementos();

       DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
       TablaVerAlumno.setModel(cabeceraDeTabla);
       TableModel listaDeDatos = TablaVerAlumno.getModel();

       for(int i=0; i<cantidadDeElementos; i++){
       Alumno profesor = controlAlumno.getListaDeAlumnos().get(i);
       listaDeDatos.setValueAt(profesor.getCarnet(), i, 0);
       listaDeDatos.setValueAt(profesor.getNombre(), i, 1);
       listaDeDatos.setValueAt(profesor.getTelefono(), i, 2);
       listaDeDatos.setValueAt(profesor.getCarrera(), i, 3);


       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTablaAlumno = new javax.swing.JScrollPane();
        TablaVerAlumno = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        TablaVerAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Carnet", "Nombre", "Telefono", "Carrera"
            }
        ));
        scrollTablaAlumno.setViewportView(TablaVerAlumno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTablaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTablaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVerAlumno;
    private javax.swing.JScrollPane scrollTablaAlumno;
    // End of variables declaration//GEN-END:variables
}
