/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeProfesor;
import org.emersonhernandez.modelo.Profesor;


/**
 *
 * @author emerh
 */
public class VistaActualizarProfesor extends javax.swing.JInternalFrame {
public static ControlDeProfesor controladorActualizarProfe = ControlDeProfesor.getInstancia();
    /**
     * Creates new form VistaActualizarProfesor
     */
    public VistaActualizarProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarnetAntiguoActualizarProfesor = new javax.swing.JLabel();
        txtCarnetAntiguoActualizarProfesor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNuevoCarnetActualizarProfesor = new javax.swing.JLabel();
        txtNuevoCarnetActualizarProfesor = new javax.swing.JTextField();
        lblNuevoNombreActualizarProfesor = new javax.swing.JLabel();
        txtNuevoNombreActualizarProfesor = new javax.swing.JTextField();
        lblNuevoMateriaActualizarProfesor = new javax.swing.JLabel();
        txtNuevoMateriaActualizarProfesor = new javax.swing.JTextField();
        lblTelefonoNuevoActualizarProfesor = new javax.swing.JLabel();
        txtTelefonoNuevoActualizarProfesor = new javax.swing.JTextField();
        botonActualizarActualizarProfesor = new javax.swing.JButton();

        setClosable(true);

        lblCarnetAntiguoActualizarProfesor.setText("Carnet Antiguo");

        lblNuevoCarnetActualizarProfesor.setText("Carnet Nuevo");

        lblNuevoNombreActualizarProfesor.setText("Nombre Nuevo");

        lblNuevoMateriaActualizarProfesor.setText("Materia Nueva");

        lblTelefonoNuevoActualizarProfesor.setText("Telefono Nuevo");

        botonActualizarActualizarProfesor.setText("Actualizar");
        botonActualizarActualizarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActualizarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarnetAntiguoActualizarProfesor)
                                .addGap(44, 44, 44)
                                .addComponent(txtCarnetAntiguoActualizarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNuevoCarnetActualizarProfesor)
                                    .addComponent(lblNuevoNombreActualizarProfesor)
                                    .addComponent(lblNuevoMateriaActualizarProfesor)
                                    .addComponent(lblTelefonoNuevoActualizarProfesor))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNuevoCarnetActualizarProfesor)
                                    .addComponent(txtNuevoNombreActualizarProfesor)
                                    .addComponent(txtNuevoMateriaActualizarProfesor)
                                    .addComponent(txtTelefonoNuevoActualizarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonActualizarActualizarProfesor)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarnetAntiguoActualizarProfesor)
                    .addComponent(txtCarnetAntiguoActualizarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoCarnetActualizarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoCarnetActualizarProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoNombreActualizarProfesor)
                    .addComponent(txtNuevoNombreActualizarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoMateriaActualizarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoMateriaActualizarProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoNuevoActualizarProfesor)
                    .addComponent(txtTelefonoNuevoActualizarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botonActualizarActualizarProfesor)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarActualizarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActualizarProfesorActionPerformed
        // TODO add your handling code here:
          Profesor nuevoProfe = new Profesor();
        int id = Integer.parseInt(txtCarnetAntiguoActualizarProfesor.getText());

        for(Profesor profesorAntiguo: controladorActualizarProfe.getListaDeProfesores()){
            if(profesorAntiguo.getCarnet()== id){
                nuevoProfe.setCarnet(Integer.parseInt(txtNuevoCarnetActualizarProfesor.getText()));
                nuevoProfe.setNombre(txtNuevoNombreActualizarProfesor.getText());
                nuevoProfe.setCarrera(txtNuevoMateriaActualizarProfesor.getText());
                nuevoProfe.setTelefono(txtTelefonoNuevoActualizarProfesor.getText());

                controladorActualizarProfe.actualizarProfesor(profesorAntiguo, nuevoProfe);
            }
        }
        this.setVisible(false);
        txtCarnetAntiguoActualizarProfesor.setText("");
        txtNuevoCarnetActualizarProfesor.setText("");
        txtNuevoNombreActualizarProfesor.setText("");
        txtNuevoMateriaActualizarProfesor.setText("");
        txtTelefonoNuevoActualizarProfesor.setText("");
    }//GEN-LAST:event_botonActualizarActualizarProfesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarActualizarProfesor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCarnetAntiguoActualizarProfesor;
    private javax.swing.JLabel lblNuevoCarnetActualizarProfesor;
    private javax.swing.JLabel lblNuevoMateriaActualizarProfesor;
    private javax.swing.JLabel lblNuevoNombreActualizarProfesor;
    private javax.swing.JLabel lblTelefonoNuevoActualizarProfesor;
    private javax.swing.JTextField txtCarnetAntiguoActualizarProfesor;
    private javax.swing.JTextField txtNuevoCarnetActualizarProfesor;
    private javax.swing.JTextField txtNuevoMateriaActualizarProfesor;
    private javax.swing.JTextField txtNuevoNombreActualizarProfesor;
    private javax.swing.JTextField txtTelefonoNuevoActualizarProfesor;
    // End of variables declaration//GEN-END:variables
}
