/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeAlumno;
import org.emersonhernandez.modelo.Alumno;

/**
 *
 * @author Emerson
 */
public class VistaAgregarAlumno extends javax.swing.JInternalFrame {
public static ControlDeAlumno controlador = ControlDeAlumno.getInstancia();

    /**
     * Creates new form VistaAgregarAlumno
     */
    public VistaAgregarAlumno() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarProfesor = new javax.swing.JPanel();
        lblIdAgregarProfesor = new javax.swing.JLabel();
        txtIdAgregarProfesor = new javax.swing.JTextField();
        lblNombreAgregarProfesor = new javax.swing.JLabel();
        txtNombreAgregarProfesor = new javax.swing.JTextField();
        lblCarreraAgregarProfesor = new javax.swing.JLabel();
        txtCarreraAgregarProfesor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botonAceptarAgregarProfesor = new javax.swing.JButton();
        botonCancelarAgregarProfesor = new javax.swing.JButton();
        lblTelefonoAgregarAlumno = new javax.swing.JLabel();
        txtTelefonoAgregarALumno = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdAgregarProfesor.setText("Carnet Alumno: ");

        lblNombreAgregarProfesor.setText("Nombre Alumno:");

        lblCarreraAgregarProfesor.setText("Carrera Alumno:");

        botonAceptarAgregarProfesor.setText("Aceptar");
        botonAceptarAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarAgregarProfesorActionPerformed(evt);
            }
        });

        botonCancelarAgregarProfesor.setText("Cancelar");
        botonCancelarAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAgregarProfesorActionPerformed(evt);
            }
        });

        lblTelefonoAgregarAlumno.setText("Telefono:");

        javax.swing.GroupLayout panelAgregarProfesorLayout = new javax.swing.GroupLayout(panelAgregarProfesor);
        panelAgregarProfesor.setLayout(panelAgregarProfesorLayout);
        panelAgregarProfesorLayout.setHorizontalGroup(
            panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                        .addComponent(botonAceptarAgregarProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelarAgregarProfesor))
                    .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                        .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                                    .addComponent(lblIdAgregarProfesor)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIdAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                                    .addComponent(lblNombreAgregarProfesor)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombreAgregarProfesor))
                                .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                                    .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCarreraAgregarProfesor)
                                        .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(lblTelefonoAgregarAlumno)))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCarreraAgregarProfesor)
                                        .addComponent(txtTelefonoAgregarALumno))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAgregarProfesorLayout.setVerticalGroup(
            panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdAgregarProfesor)
                    .addComponent(txtIdAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAgregarProfesor)
                    .addComponent(txtNombreAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarreraAgregarProfesor)
                    .addComponent(txtCarreraAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoAgregarAlumno)
                    .addComponent(txtTelefonoAgregarALumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarAgregarProfesor)
                    .addComponent(botonCancelarAgregarProfesor))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAgregarProfesorActionPerformed
    this.setVisible(false);   
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarAgregarProfesorActionPerformed

    private void botonAceptarAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarAgregarProfesorActionPerformed
        Alumno miProfesor = new Alumno();      
        miProfesor.setCarnet(Integer.parseInt(txtIdAgregarProfesor.getText()));
        miProfesor.setNombre(txtNombreAgregarProfesor.getText());
        miProfesor.setCarrera(txtCarreraAgregarProfesor.getText()); 
        miProfesor.setTelefono(txtTelefonoAgregarALumno.getText()); 

        controlador.agregarAlumno(miProfesor); 

        this.setVisible(false);
        txtIdAgregarProfesor.setText("");
        txtNombreAgregarProfesor.setText("");
        txtCarreraAgregarProfesor.setText("");
        txtTelefonoAgregarALumno.setText("");


  // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptarAgregarProfesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarAgregarProfesor;
    private javax.swing.JButton botonCancelarAgregarProfesor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCarreraAgregarProfesor;
    private javax.swing.JLabel lblIdAgregarProfesor;
    private javax.swing.JLabel lblNombreAgregarProfesor;
    private javax.swing.JLabel lblTelefonoAgregarAlumno;
    private javax.swing.JPanel panelAgregarProfesor;
    private javax.swing.JTextField txtCarreraAgregarProfesor;
    private javax.swing.JTextField txtIdAgregarProfesor;
    private javax.swing.JTextField txtNombreAgregarProfesor;
    private javax.swing.JTextField txtTelefonoAgregarALumno;
    // End of variables declaration//GEN-END:variables

   
}
