/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;


import org.emersonhernandez.modelo.Profesor;
import org.emersonhernandez.controlador.ControlDeProfesor;


/**
 *
 * @author emerh
 */
public class VistaAgregarProfesor extends javax.swing.JInternalFrame {
public static ControlDeProfesor controlador = ControlDeProfesor.getInstancia();

    /**
     * Creates new form VistaAgregarProfesor
     */
    public VistaAgregarProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCarnetProfesor = new javax.swing.JLabel();
        txtCarnetProfesor = new javax.swing.JTextField();
        lblNombreProfesor = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        lblCarreraProfesor = new javax.swing.JLabel();
        txtCarreraProfesor = new javax.swing.JTextField();
        lblTelefonoProfesor = new javax.swing.JLabel();
        txtTelefonoProfesor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botonAceptarAgregarProfesor = new javax.swing.JButton();
        botonCancelarAgregarProfesor = new javax.swing.JButton();

        lblCarnetProfesor.setText("Carnet Profesor");

        lblNombreProfesor.setText("Nombre Profesor");

        lblCarreraProfesor.setText("Materia ");

        lblTelefonoProfesor.setText("Telefono");

        botonAceptarAgregarProfesor.setText("Aceptar");
        botonAceptarAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarAgregarProfesorActionPerformed(evt);
            }
        });

        botonCancelarAgregarProfesor.setText("Cancelar");
        botonCancelarAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAgregarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAceptarAgregarProfesor)
                        .addGap(159, 159, 159)
                        .addComponent(botonCancelarAgregarProfesor))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarnetProfesor)
                            .addComponent(lblNombreProfesor)
                            .addComponent(lblCarreraProfesor)
                            .addComponent(lblTelefonoProfesor))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCarnetProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtNombreProfesor)
                            .addComponent(txtCarreraProfesor)
                            .addComponent(txtTelefonoProfesor))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarnetProfesor)
                    .addComponent(txtCarnetProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProfesor)
                    .addComponent(txtNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarreraProfesor)
                    .addComponent(txtCarreraProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoProfesor)
                    .addComponent(txtTelefonoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptarAgregarProfesor)
                    .addComponent(botonCancelarAgregarProfesor))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAgregarProfesorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarAgregarProfesorActionPerformed

    private void botonAceptarAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarAgregarProfesorActionPerformed
        // TODO add your handling code here:
        Profesor miProfesor = new Profesor();      
        miProfesor.setCarnet(Integer.parseInt(txtCarnetProfesor.getText()));
        miProfesor.setNombre(txtNombreProfesor.getText());
        miProfesor.setCarrera(txtCarreraProfesor.getText()); 
        miProfesor.setTelefono(txtTelefonoProfesor.getText()); 

        controlador.agregarProfesor(miProfesor); 

        this.setVisible(false);
        txtCarnetProfesor.setText("");
        txtNombreProfesor.setText("");
        txtCarreraProfesor.setText("");
    }//GEN-LAST:event_botonAceptarAgregarProfesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarAgregarProfesor;
    private javax.swing.JButton botonCancelarAgregarProfesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCarnetProfesor;
    private javax.swing.JLabel lblCarreraProfesor;
    private javax.swing.JLabel lblNombreProfesor;
    private javax.swing.JLabel lblTelefonoProfesor;
    private javax.swing.JTextField txtCarnetProfesor;
    private javax.swing.JTextField txtCarreraProfesor;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JTextField txtTelefonoProfesor;
    // End of variables declaration//GEN-END:variables
}
