/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeCursos;
import org.emersonhernandez.modelo.Cursos;


/**
 *
 * @author emerh
 */
public class VistaActualizarCurso extends javax.swing.JInternalFrame {
public static ControlDeCursos  controlActualizarCursos = ControlDeCursos.getInstancia();
    /**
     * Creates new form VistaActualizarCurso
     */
    public VistaActualizarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAntiguoIdActualizarCurso = new javax.swing.JLabel();
        txtAntiguoIdActualizarCurso = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNuevoIdActualizarCurso = new javax.swing.JLabel();
        txtNuevoIdActualizarCurso = new javax.swing.JTextField();
        lblNuevoNombreActualizarCurso = new javax.swing.JLabel();
        txtNuevoNombreActualizarCurso = new javax.swing.JTextField();
        lblNuevaCarreraActualizarCurso = new javax.swing.JLabel();
        txtNuevaCarreraActualizarCurso = new javax.swing.JTextField();
        lblNuevoProfesorActualizarCurso = new javax.swing.JLabel();
        txtNuevoProfesorActualizarCurso = new javax.swing.JTextField();
        botonActualizarCurso = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblAntiguoIdActualizarCurso.setText("Antiguo ID");

        lblNuevoIdActualizarCurso.setText("Nuevo ID");

        lblNuevoNombreActualizarCurso.setText("Nombre Nuevo");

        lblNuevaCarreraActualizarCurso.setText("Carrera Nueva");

        lblNuevoProfesorActualizarCurso.setText("Profesor Nuevo");

        botonActualizarCurso.setText("Actualizar");
        botonActualizarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNuevoIdActualizarCurso)
                                    .addComponent(lblNuevoNombreActualizarCurso)
                                    .addComponent(lblNuevaCarreraActualizarCurso)
                                    .addComponent(lblNuevoProfesorActualizarCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNuevaCarreraActualizarCurso)
                                        .addComponent(txtNuevoProfesorActualizarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addComponent(txtNuevoNombreActualizarCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(txtNuevoIdActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonActualizarCurso)
                                        .addGap(87, 87, 87))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAntiguoIdActualizarCurso)
                                .addGap(85, 85, 85)
                                .addComponent(txtAntiguoIdActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntiguoIdActualizarCurso)
                    .addComponent(txtAntiguoIdActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoIdActualizarCurso)
                    .addComponent(txtNuevoIdActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoNombreActualizarCurso)
                    .addComponent(txtNuevoNombreActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevaCarreraActualizarCurso)
                    .addComponent(txtNuevaCarreraActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoProfesorActualizarCurso)
                    .addComponent(txtNuevoProfesorActualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonActualizarCurso)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarCursoActionPerformed
        // TODO add your handling code here:
          Cursos newCurso = new Cursos();
        int id = Integer.parseInt(txtAntiguoIdActualizarCurso.getText());

        for(Cursos cursoAntiguo: controlActualizarCursos.getListaDeCursos()){
            if(cursoAntiguo.getId()== id){
                newCurso.setId(Integer.parseInt(txtNuevoIdActualizarCurso.getText()));
                newCurso.setNombre(txtNuevoNombreActualizarCurso.getText());
                newCurso.setCarrera(txtNuevaCarreraActualizarCurso.getText());
                newCurso.setProfesor(txtNuevoProfesorActualizarCurso.getText());

                controlActualizarCursos.actualizarCurso(cursoAntiguo, newCurso);
            }
        }
        this.setVisible(false);
        txtAntiguoIdActualizarCurso.setText("");
        txtNuevoIdActualizarCurso.setText("");
        txtNuevoNombreActualizarCurso.setText("");
        txtNuevaCarreraActualizarCurso.setText("");
        txtNuevoProfesorActualizarCurso.setText(""); 
    }//GEN-LAST:event_botonActualizarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAntiguoIdActualizarCurso;
    private javax.swing.JLabel lblNuevaCarreraActualizarCurso;
    private javax.swing.JLabel lblNuevoIdActualizarCurso;
    private javax.swing.JLabel lblNuevoNombreActualizarCurso;
    private javax.swing.JLabel lblNuevoProfesorActualizarCurso;
    private javax.swing.JTextField txtAntiguoIdActualizarCurso;
    private javax.swing.JTextField txtNuevaCarreraActualizarCurso;
    private javax.swing.JTextField txtNuevoIdActualizarCurso;
    private javax.swing.JTextField txtNuevoNombreActualizarCurso;
    private javax.swing.JTextField txtNuevoProfesorActualizarCurso;
    // End of variables declaration//GEN-END:variables
}
