/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.controlador.ControlDeCarrera;
import org.emersonhernandez.modelo.Carrera;
/**
 *
 * @author emerh
 */
public class VistaAgregarCarrera extends javax.swing.JInternalFrame {
    public static ControlDeCarrera controlCarrera = ControlDeCarrera.getInstancia();

    /**
     * Creates new form VistaAgregarCarrera
     */
    public VistaAgregarCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelAgregarCarrera = new javax.swing.JPanel();
        lblIdAgregarCarrera = new javax.swing.JLabel();
        txtIdAgregarCarrera = new javax.swing.JTextField();
        lblNombreAgregarCarrera = new javax.swing.JLabel();
        txtNomgreAgregarCarrera = new javax.swing.JTextField();
        lblSeccionAgregarCarrera = new javax.swing.JLabel();
        txtSeccionAgregarCarrera = new javax.swing.JTextField();
        botonCancelarAgregarCarrera = new javax.swing.JButton();
        botonAceptarAgregarCarrera = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        lblIdAgregarCarrera.setText("Id Carrera");

        lblNombreAgregarCarrera.setText("Nombre Carrera");

        lblSeccionAgregarCarrera.setText("Seccion ");

        botonCancelarAgregarCarrera.setText("Cancelar");
        botonCancelarAgregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAgregarCarreraActionPerformed(evt);
            }
        });

        botonAceptarAgregarCarrera.setText("Aceptar");
        botonAceptarAgregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarAgregarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarCarreraLayout = new javax.swing.GroupLayout(panelAgregarCarrera);
        panelAgregarCarrera.setLayout(panelAgregarCarreraLayout);
        panelAgregarCarreraLayout.setHorizontalGroup(
            panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarCarreraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarCarreraLayout.createSequentialGroup()
                        .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAceptarAgregarCarrera)
                            .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdAgregarCarrera)
                                .addComponent(lblNombreAgregarCarrera)
                                .addComponent(lblSeccionAgregarCarrera)))
                        .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarCarreraLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdAgregarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(txtNomgreAgregarCarrera)
                                    .addComponent(txtSeccionAgregarCarrera)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarCarreraLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelarAgregarCarrera)
                                .addGap(14, 14, 14))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelAgregarCarreraLayout.setVerticalGroup(
            panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarCarreraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdAgregarCarrera)
                    .addComponent(txtIdAgregarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAgregarCarrera)
                    .addComponent(txtNomgreAgregarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeccionAgregarCarrera)
                    .addComponent(txtSeccionAgregarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelAgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarAgregarCarrera)
                    .addComponent(botonCancelarAgregarCarrera))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarAgregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAgregarCarreraActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarAgregarCarreraActionPerformed

    private void botonAceptarAgregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarAgregarCarreraActionPerformed
        // TODO add your handling code here:
        Carrera miCarrera = new Carrera();      
        miCarrera.setCarnet(Integer.parseInt(txtIdAgregarCarrera.getText()));
        miCarrera.setNombre(txtNomgreAgregarCarrera.getText());
        miCarrera.setSeccion(txtSeccionAgregarCarrera.getText()); 
        
        

        controlCarrera.agregarCarrera(miCarrera); 

        this.setVisible(false);
        txtIdAgregarCarrera.setText("");
        txtNomgreAgregarCarrera.setText("");
        txtSeccionAgregarCarrera.setText("");
        
        
    }//GEN-LAST:event_botonAceptarAgregarCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarAgregarCarrera;
    private javax.swing.JButton botonCancelarAgregarCarrera;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdAgregarCarrera;
    private javax.swing.JLabel lblNombreAgregarCarrera;
    private javax.swing.JLabel lblSeccionAgregarCarrera;
    private javax.swing.JPanel panelAgregarCarrera;
    private javax.swing.JTextField txtIdAgregarCarrera;
    private javax.swing.JTextField txtNomgreAgregarCarrera;
    private javax.swing.JTextField txtSeccionAgregarCarrera;
    // End of variables declaration//GEN-END:variables
}
