/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.emersonhernandez.vista;
import org.emersonhernandez.modelo.Carrera;
import org.emersonhernandez.controlador.ControlDeCarrera;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author emerh
 */
public class VistaVerCarrera extends javax.swing.JInternalFrame {
    public static ControlDeCarrera controlaCarrera = ControlDeCarrera.getInstancia();

    /**
     * Creates new form VistaVerCarrera
     */
    public VistaVerCarrera() {
        initComponents();
    }
    public void verCarreras(){
       String [] encabezados = {"ID","Nombre","Seccion"};
       int cantidadDeElementos = controlaCarrera.cantidadDeCarreras();

       DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
       TablaVerCarrera.setModel(cabeceraDeTabla);
       TableModel listaDeDatos = TablaVerCarrera.getModel();

       for(int i=0; i<cantidadDeElementos; i++){
       Carrera carrerita = controlaCarrera.getListaDeCarreras().get(i);
       listaDeDatos.setValueAt(carrerita.getId(), i, 0);
       listaDeDatos.setValueAt(carrerita.getNombre(), i, 1);
       listaDeDatos.setValueAt(carrerita.getSeccion(), i, 2);
   


       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVerCarrera = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        TablaVerCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Carrera", "Nombre Carrera", "Seccion"
            }
        ));
        jScrollPane1.setViewportView(TablaVerCarrera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVerCarrera;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
